const months = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

const years = Array.from({ length: 20 }, (_, i) => new Date().getFullYear() + i);

export const costSheetFields = [
  { id: "dateUpdateCostSheet", label: "Update date", type: "date" },
  { id: "developerName", label: "Developer Name" },
  { id: "projectName", label: "Project Name" },
  { id: "location", label: "Location" },
  { id: "subLocation", label: "Sub-Location" },
  { id: "road", label: "Road" },
  { id: "landmark", label: "Landmark" },
  { id: "flatsPerFloor", label: "Flats per Floor" },
  { id: "pinCode", label: "Pin Code" },
  { id: "station", label: "Station" },
  { id: "district", label: "District" },
  { id: "state", label: "State" },
  { id: "landParcel", label: "Land Parcel (in acre)" },
  { id: "towers", label: "No. of Towers" },
  { id: "storey", label: "Storey" },

  { id: "wingBuildingNo", label: "Wing / Building No." },
  {
    id: "projectStatus",
    label: "Project Status",
    type: "dropdown",
    options: ["Under Construction", "Ready to Move", "OC Received"],
  },
  {
    id: "flatType",
    label: "BHK Type",
    type: "dropdown",
    options: [
      "1 RK",
      "1 BHK",
      "1.5 BHK",
      "2 BHK",
      "2.5 BHK",
      "3 BHK",
      "3.5 BHK",
      "4 BHK",
      "4.5 BHK",
      "5 BHK",
      "Row House",
      "Bunglow",
      "Villa",
      "Penthouse",
    ],
  },
  { id: "saleableArea", label: "Saleable Area" },
  { id: "reraCarpet", label: "RERA Carpet / Usable Carpet" },
  { id: "psfRate", label: "Per Sq. ft. Rate" },
  { id: "avRate", label: "Agreement Value Rate" },
  {
    id: "floorRise",
    label: "Floor Rise / Floor Band",
    type: "dropdown",
    options: ["Floor Rise", "FR - Fixed Rate", "Floor Band"],
  },
  { id: "registration", label: "Registration Fees" },
  { id: "description", label: "Description", type: "textarea" },

  { id: "fixedComponent", label: "Fixed Component" },
  { id: "possessionCharges", label: "Possession Charges" },
  { id: "parkingCharge", label: "Parking Charges" },
  { id: "totalPackage", label: "Total Package" },
  { id: "paymentScheme", label: "Payment Schemes", type: "multi-input" },

  {
    id: "apartmentAmenities",
    label: "Apartment Amenities",
    type: "multi-select",
    options: [
      "Air Conditioner",
      "Aqua Guard",
      "Branded Electrical Switches & Fittings",
      "Chimney",
      "Designer Door",
      "Door Bell",
      "Electrical fittings",
      "False Cealing",
      "Floor Ceiling Heights",
      "Geyser",
      "Intercom facility",
      "Kitchen Platform with Sink",
      "Marble & Granite Window Frame",
      "Modular Kitchen",
      "Quality Cp & Sanitary Fittings",
      "Tiles Flooring All room",
      "Video door phone",
      "Water Tank",
    ],
  },
  {
    id: "projectAmenities",
    label: "Project Amenities",
    type: "multi-select",
    options: [
      "Aerobic/Dance studio",
      "Basketball Court",
      "Bedminton Court",
      "Benquate Hall",
      "Bio Metric Entrance Lobby",
      "CCTV Camera",
      "Cabansa Seating",
      "Cafetearea",
      "Club House",
      "Cricket Turf",
      "Double Highted Designer Lobby",
      "EV Charging Points",
      "Fire Safety",
      "Fitness area",
      "Football Turf",
      "Gazebo",
      "Guest Rooms",
      "Gymnasium",
      "High Speed Elevators",
      "Indoor games",
      "Jogging and Walking Track",
      "Kids Play Area",
      "Kids Pool",
      "Land Scaped Garden",
      "Library",
      "Meditation Area",
      "Mini Theatre",
      "Multipurpose Court",
      "Multipurpose lawn",
      "Pool Side Deck",
      "Power Backup",
      "Reflexology Path",
      "Seating Area",
      "Senior Citizen Area",
      "Sketting Ring",
      "Solar Water System",
      "Spa",
      "Steam Room",
      "Swimming Pool",
      "Theme Garden",
      "Toddlers Play Area",
      "Yoga Area",
    ],
  },
  {
    id: "locationHighlights",
    label: "Location Highlights",
    type: "multi-select",
    options: [
      "Bandra Worli Sea Link",
      "Banks & ATM",
      "Chhatrapati Shivaji Maharaj International Airport",
      "Club, Hotels & Restaurants",
      "College & School",
      "D'Mart",
      "Domestic Airport",
      "Eastern Express Highway",
      "Hospitals and Medicals",
      "International Airport",
      "LINK ROAD",
      "Market",
      "Metro Station",
      "Mumbai - Ahmadabad Express Highway",
      "Municipal Ground",
      "Multiplex Theatres",
      "National Highway",
      "Railway Station",
      "Sanjay Gandhi National Park",
      "Shopping Mall",
      "Smart Bazar , Star Bazar",
      "Sports Complex",
      "Western Express Highway",
    ],
  },

  {
    id: "type",
    label: "Project Type",
    type: "dropdown",
    options: ["New", "Redevelopment", "SRA", "Pre-launch"],
  },
  { id: "mahaReraNumber", label: "Maha RERA Number" },
  { id: "mahaReraLink", label: "Maha RERA Link" },
  {
    id: "possessionMonth",
    label: "Possession Month",
    type: "dropdown",
    options: months,
  },
  {
    id: "possessionYear",
    label: "Possession Year",
    type: "dropdown",
    options: years.map(String),
  },
  { id: "reraPossession", label: "Rera Possession", type: "date" },
  {
    id: "isCosmo",
    label: "Is Cosmo?",
    type: "dropdown",
    options: ["Yes", "No"],
  },
  {
    id: "availibility",
    label: "Availibility",
    type: "dropdown",
    options: ["Available", "Sold Out"],
  },
  { id: "imageUrl", label: "Image URL" },
  { id: "videoUrl", label: "Video URL" },
  { id: "siteHeadName", label: "Site Head Name" },
  { id: "siteHeadNumber", label: "Site Head Number" },
];
